const dict = {
  en: {
    close_drawer: "Close drawer",
    name: "Name",
    capacity: "Capacity",
    fee: "Fee",
    parking_lot_name: "Parking lot name",
    parking_lot_capacity: "Parking lot capacity",
    parking_lot_hourly_fee: "Parking lot hourly fee",
    RON: "RON",
    submit: "Submit",
    country: "Country",
    city: "City",
    street: "Street",
    success: "Success",
    close: "Close",
    delete: "Delete",
    edit: "Edit",
    close_modal: "Close modal",
    are_you_sure: "Are you sure?",
    available_spaces: "available spaces",
    occupied_spaces: "occupied spaces",
    spaces: "spaces",
    reserve: "Reserve",
    cancel: "Cancel",
    missing_or_invalid_values: "Missing or invalid values",
  },
};

export default dict;
